const HANZI_ITEMS = [
  { char: "山", pinyin: "shan", word: "大山", group: "自然" },
  { char: "水", pinyin: "shui", word: "喝水", group: "自然" },
  { char: "火", pinyin: "huo", word: "火苗", group: "自然" },
  { char: "木", pinyin: "mu", word: "木头", group: "自然" },
  { char: "日", pinyin: "ri", word: "太阳", group: "自然" },
  { char: "月", pinyin: "yue", word: "月亮", group: "自然" },
  { char: "云", pinyin: "yun", word: "白云", group: "自然" },
  { char: "雨", pinyin: "yu", word: "下雨", group: "自然" },
  { char: "白", pinyin: "bai", word: "白云", group: "自然" },
  { char: "田", pinyin: "tian", word: "田地", group: "自然" },
  { char: "花", pinyin: "hua", word: "小花", group: "自然" },
  { char: "草", pinyin: "cao", word: "小草", group: "自然" },
  { char: "人", pinyin: "ren", word: "大人", group: "生活" },
  { char: "大", pinyin: "da", word: "大的", group: "生活" },
  { char: "小", pinyin: "xiao", word: "小的", group: "生活" },
  { char: "口", pinyin: "kou", word: "嘴巴", group: "身体" },
  { char: "手", pinyin: "shou", word: "小手", group: "身体" },
  { char: "目", pinyin: "mu", word: "眼睛", group: "身体" },
  { char: "耳", pinyin: "er", word: "耳朵", group: "身体" },
  { char: "牛", pinyin: "niu", word: "小牛", group: "动物" },
  { char: "羊", pinyin: "yang", word: "小羊", group: "动物" },
  { char: "马", pinyin: "ma", word: "小马", group: "动物" },
  { char: "鸟", pinyin: "niao", word: "小鸟", group: "动物" },
  { char: "鱼", pinyin: "yu", word: "小鱼", group: "动物" },
  { char: "虫", pinyin: "chong", word: "小虫", group: "动物" },
  { char: "车", pinyin: "che", word: "小车", group: "生活" },
  { char: "门", pinyin: "men", word: "大门", group: "生活" },
  { char: "书", pinyin: "shu", word: "看书", group: "生活" },
  { char: "米", pinyin: "mi", word: "米饭", group: "生活" },
  { char: "爸", pinyin: "ba", word: "爸爸", group: "家庭" },
  { char: "妈", pinyin: "ma", word: "妈妈", group: "家庭" },
];

const WORD_PAIRS = [
  { word: "小羊", parts: ["小", "羊"] },
  { word: "小鱼", parts: ["小", "鱼"] },
  { word: "小鸟", parts: ["小", "鸟"] },
  { word: "大山", parts: ["大", "山"] },
  { word: "山水", parts: ["山", "水"] },
  { word: "白云", parts: ["白", "云"] },
  { word: "小车", parts: ["小", "车"] },
  { word: "大门", parts: ["大", "门"] },
];
